operator:
  type: 'mha'
  name: "swa"
  config_filepath: ../configs/sequence_mixers/swa.yaml


sample_config:
  seed: 0
  dit_model_name: DiT-XL/2
  grafted_dit_ckpt_path: ../grafted_models/dit-xl2-mha-swa-75p-fid3.09/model.pt
  samples_save_dir: results/dit-xl2-mha-swa-50p-graftfusion75
  image_size: 256
  graft_indexes:
    - 1
    - 2
    - 5
    - 7
    - 10
    - 11
    - 13
    - 15
    - 18
    - 19
    - 21
    - 22
    - 25
    - 27
  graft_weights:


